[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chamfer-distance-tensorflow"
version = "0.1.0"
authors = [
  { name="Daniyar Kazbek", email="daniyar1509@gmail.com" },
]

readme = "README.md"
requires-python = ">=3.8"
dependencies = ["tensorflow>=2.18.0"]

[tool.setuptools]
packages = ["chamfer_dist_tensorflow"]

[tool.setuptools.package-data]
chamfer_dist_tensorflow = ["*.so", "*.cu", "*.cc", "*.sh"]